//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.DAL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExTest()
        {
            this.ExTest_Question = new HashSet<ExTest_Question>();
        }
    
        public int Id { get; set; }
        public System.DateTime ExecutionDate { get; set; }
        public string Name { get; set; }
        public Nullable<int> TestId { get; set; }
        public byte State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExTest_Question> ExTest_Question { get; set; }
        public virtual Test Test { get; set; }
    }
}
